### ISSUE TITLE
pixel scale missing in SimCamera._create_header

### ISSUE THREAD

**Issue by masurt** [pyobs/pyobs-core#21]
Sollte die richtige formel sein:

` hdr['CDELT1'] = ((206.265 * self.pixel_size * 1000)/self.telescope.focal_length/3600,  "Scale of detector pixels [deg/pixel]")`

siehe https://astrojolo.com/gears/pixel-scale-and-resolution/

**Comment by thusser** [comment]
Pixel scale, like many other FITS headers, is calculated in BaseCamera, not in the simulation:
https://github.com/pyobs/pyobs-core/blob/master/pyobs/modules/camera/basecamera.py#L187
