### ISSUE TITLE
world.py imports photutils which is only an optional requirement

### ISSUE THREAD

**Issue by karlwessel** [pyobs/pyobs-core#24]
Importing `BaseTelescope` or any other module which at some point import world.py fails because it can't import `photutils` since it is only listed as an optional requirement.

**Comment by karlwessel** [comment]
This can be tested by starting the `DummyTelescope` module with
```
pyobs dummytelescope.yml
```

where `dummytelescope.yml` only contains
```
class: pyobs.modules.telescope.dummytelescope.DummyTelescope
```

**Comment by karlwessel** [comment]
Should we just make `photutils` a required dependency?

**Comment by thusser** [comment]
Yes
