### ISSUE TITLE
Inconsistent offset output

### ISSUE THREAD

**Issue by GermanHydrogen** [pyobs/pyobs-core#329]
Offset is set as a string "offsets" in `FitsHeaderOffsets` https://github.com/pyobs/pyobs-core/blob/4478c3280307571db9e5110782c1ae61bfb95466/pyobs/images/processors/offsets/fitsheader.py#L40
Is this intentional or is the class depricated?

**Comment by GermanHydrogen** [comment]
This is apparently also the case in `NStarOffsets`
https://github.com/pyobs/pyobs-core/blob/4478c3280307571db9e5110782c1ae61bfb95466/pyobs/images/processors/offsets/nstar.py#L89

**Comment by thusser** [comment]
Deprecated, should be changed to the new class-based offsets.

**Comment by GermanHydrogen** [comment]
Closed by PR #332
